### ISSUE TITLE
TypeError: netcat() missing 2 required positional arguments: 'randomAgent' and 'header'

### ISSUE THREAD

**Issue by lordcris** [MrH0wl/Cloudmare#28]
Hello I get this error when running the script on python-3.7.9 or python-3.6.12

```
python Cloudmare.py -u example.com

...

[?]Retrieving target homepage at: http://example.com
   [+]http://example.com Rirects to https://example.com/
Traceback (most recent call last):
  File "Cloudmare.py", line 79, in <module>
    IPscan(args.domain, host, A, args.uagent, args.randomAgent, args.headers, args)
  File "/Cloudmare/lib/analyzer/ipscan.py", line 50, in IPscan
    netcat(domain, ns, args.ignoreRedirects, args.headers, count=+1)
TypeError: netcat() missing 2 required positional arguments: 'randomAgent' and 'header'
```

**Comment by PatchByte** [comment]
Here take a look at the fix: https://github.com/MrH0wl/Cloudmare/pull/30/commits/ea521289c45a36b66c236cd43fdc9f11114e8a69
