### ISSUE TITLE
Error - Traceback - Max retries exceeded with url

### ISSUE THREAD

**Issue by asheroto** [mrh0wl/Cloudmare#40]
Thanks for the tool! I'm getting this error, tried a few sites...

**Command:**
```
PS C:\Users\User\Downloads\Cloudmare> python Cloudmare.py -u target.site --bruter -sC -sSh -sSt --host SITE_HERE
```

**Output:**
```
  ____ _                 _ __  __
 / ___| | ___  _   _  __| |  \/  | __ _ _ __ ___
| |   | |/ _ \| | | |/ _` | |\/| |/ _` | '__/ _ \
| |___| | (_) | |_| | (_| | |  | | (_| | | |  __/
 \____|_|\___/ \__,_|\__,_|_|  |_|\__,_|_|  \___| [2.1.10.11]
Automatic CloudProxy and Reverse Proxy bypass tool
##################################################

[*]Enumerating subdomains now for target.site
[*]Enumerating misconfigured subdomains
   [!]Total Misconfigured Subdomains Found: 0
      [-]misconfigured subdomains not found
Traceback (most recent call last):
  File "C:\Users\User\Downloads\Cloudmare\thirdparty\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\User\Downloads\Cloudmare\thirdparty\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Downloads\Cloudmare\thirdparty\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\User\Downloads\Cloudmare\thirdparty\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\User\Downloads\Cloudmare\thirdparty\urllib3\connection.py", line 187, in connect
    conn = self._new_conn()
  File "C:\Users\User\Downloads\Cloudmare\thirdparty\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
thirdparty.urllib3.exceptions.NewConnectionError: <thirdparty.urllib3.connection.HTTPConnection object at 0x000001E67CCD9D50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Downloads\Cloudmare\thirdparty\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\User\Downloads\Cloudmare\thirdparty\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Users\User\Downloads\Cloudmare\thirdparty\urllib3\util\retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
thirdparty.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='target.site', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<thirdparty.urllib3.connection.HTTPConnection object at 0x000001E67CCD9D50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Downloads\Cloudmare\Cloudmare.py", line 47, in <module>
    nameservers = nameserver(args.domain)
  File "C:\Users\User\Downloads\Cloudmare\lib\tools\bruter.py", line 46, in nameserver
    checking = bruter(domain)
  File "C:\Users\User\Downloads\Cloudmare\lib\tools\bruter.py", line 29, in bruter
    page = requests.get(url, timeout=config['http_timeout_seconds'])
  File "C:\Users\User\Downloads\Cloudmare\thirdparty\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\User\Downloads\Cloudmare\thirdparty\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\User\Downloads\Cloudmare\thirdparty\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\User\Downloads\Cloudmare\thirdparty\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\User\Downloads\Cloudmare\thirdparty\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
thirdparty.requests.exceptions.ConnectionError: HTTPConnectionPool(host='target.site', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<thirdparty.urllib3.connection.HTTPConnection object at 0x000001E67CCD9D50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
PS C:\Users\User\Downloads\Cloudmare>
```

**Comment by mrh0wl** [comment]
Hi, check your target connection, I tried several websites and it works in all of them
