### ISSUE TITLE
error start

### ISSUE THREAD

**Issue by listmen001** [mrh0wl/Cloudmare#54]
command:
python Cloudmare.py -u target.site --bruter -sC -sSh -sSt --host 'dashboard.0x.org'

answer:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/forest/PycharmProjects/FREELANCE_22.04.2021/awaiting_execution/kwork_89 ?/kwork_89_data/Cloudmare/Cloudmare/lib/tools/sublist3r.py", line 260, in run
    domain_list = self.enumerate()
                  ^^^^^^^^^^^^^^^^
  File "/home/forest/PycharmProjects/FREELANCE_22.04.2021/awaiting_execution/kwork_89 ?/kwork_89_data/Cloudmare/Cloudmare/lib/tools/sublist3r.py", line 738, in enumerate
    resp = json.loads(resp)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not int

**Comment by memmedrehimzade** [comment]
+
