### ISSUE TITLE
ImportError: No module named w3lib.html !

### ISSUE THREAD

**Issue by tungpdv** [MrH0wl/Cloudmare#7]
When i run this like : python cloudmare.py had error : 

Traceback (most recent call last):
  File "Cloudmare.py", line 33, in <module>
    from thirdparty.html_similarity import similarity
  File "/home/tungpdv/Desktop/Hacking/Cloudmare/thirdparty/html_similarity/__init__.py", line 4, in <module>
    from thirdparty.html_similarity.style_similarity import style_similarity
  File "/home/tungpdv/Desktop/Hacking/Cloudmare/thirdparty/html_similarity/style_similarity.py", line 1, in <module>
    from thirdparty.parsel import Selector
  File "/home/tungpdv/Desktop/Hacking/Cloudmare/thirdparty/parsel/__init__.py", line 10, in <module>
    from thirdparty.parsel.selector import Selector, SelectorList  # NOQA
  File "/home/tungpdv/Desktop/Hacking/Cloudmare/thirdparty/parsel/selector.py", line 9, in <module>
    from .utils import flatten, iflatten, extract_regex, shorten
  File "/home/tungpdv/Desktop/Hacking/Cloudmare/thirdparty/parsel/utils.py", line 3, in <module>
    from w3lib.html import replace_entities as w3lib_replace_entities
ImportError: No module named w3lib.html

Please help me fix it .

**Comment by MrH0wl** [comment]
Use on terminal:
pip install scrapy

If this doesn’t work, use:
pip install w3lib
